### ISSUE TITLE
Fix references for Nowasad et al.

### ISSUE THREAD

**Issue by pepaaran** [khufkens/handfull_of_pixels#3]
In the book, a few times the reference for Nowasad et al is mentioned, followed by (REFERENCE) or (FIX REF). It would be nice to fix that.

**Comment by khufkens** [comment]
Thanks for the pull request on this.

**Comment by pepaaran** [comment]
Oh, I used the wrong reference for the issue, it was referring to Issue #7

**Comment by khufkens** [comment]
No worries. Thanks for all the proofreading, feedback.
